#ifndef _INPUTCONSTANTS_H
#define _INPUTCONSTANTS_H

namespace InputMapping
{
	enum EAction
	{
		ACTION_ZERO,
		ACTION_ONE,
		ACTION_TWO,
		ACTION_THREE,
		ACTION_FOUR,
		ACTION_FIVE,
		ACTION_SIX,
		ACTION_SEVEN,
		ACTION_EIGHT,
		ACTION_NINE,
		ACTION_TEN,
		ACTION_ELEVEN,
		ACTION_TWELVE,
		ACTION_THIRTEEN,
		ACTION_FOURTEEN,
		ACTION_FIVETEEN,
		ACTION_SIXTEEN,
		ACTION_SEVENTEEN,
		ACTION_EIGHTTEEN,
		ACTION_NINETEEN,
		ACTION_TWENTY,
		ACTION_TWENTY_ONE,
		ACTION_TWENTY_TWO,
		ACTION_TWENTY_THREE,
		ACTION_TWENTY_FOUR,
		ACTION_TWENTY_FIVE,
		ACTION_TWENTY_SIX,
		ACTION_TWENTY_SEVEN,
		ACTION_TWENTY_EIGHT,
		ACTION_TWENTY_NINE,
		ACTION_THIRTY,
		ACTION_THIRTY_ONE,
		ACTION_THIRTY_TWO,
		ACTION_THIRTY_THREE,
		ACTION_THIRTY_FOUR,
		ACTION_THIRTY_FIVE,
		ACTION_THIRTY_SIX,
		ACTION_THIRTY_SEVEN,
		ACTION_THIRTY_EIGHT,
		ACTION_THIRTY_NINE,
		ACTION_FORTY
	};

	enum EState
	{
		STATE_ONE,
		STATE_TWO,
		STATE_THREE,
		STATE_FOUR,
	};

	enum ERange
	{
		RANGE_ONE,
		RANGE_TWO,
		RANGE_THREE,
	};
}

#endif

